#!/usr/bin/env python3
"""Generate a deterministic plain-text GAAM specification publication."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "specification" / "governance-authority-assurance-metamodel.md"
RELEASE = ROOT / "release.json"

FRONT_MATTER = re.compile(r"\\A---\\n.*?\\n---\\n", re.DOTALL)
LIQUID_INCLUDE = re.compile(r"^\\s*\\{%\\s*include\\s+[^%]+%\\}\\s*$")
INLINE_LINK = re.compile(r"\\[([^\\]]+)\\]\\(([^)]+)\\)")
AUTOLINK = re.compile(r"<((?:https?|mailto):[^>]+)>")
EMPHASIS = re.compile(r"(?<!\\\\)(?:\\*\\*|__)(.+?)(?:\\*\\*|__)|(?<!\\\\)(?:\\*|_)(.+?)(?:\\*|_)")
INLINE_CODE = re.compile(r"`([^`]+)`")
HEADING = re.compile(r"^(#{1,6})\\s+(.*)$")


def strip_inline(text: str) -> str:
    text = INLINE_LINK.sub(lambda m: f"{m.group(1)} <{m.group(2)}>", text)
    text = AUTOLINK.sub(lambda m: m.group(1), text)
    text = INLINE_CODE.sub(lambda m: m.group(1), text)
    while True:
        updated = EMPHASIS.sub(lambda m: m.group(1) or m.group(2) or "", text)
        if updated == text:
            break
        text = updated
    return text.replace("\\\\*", "*").replace("\\\\_", "_").replace("\\\\`", "`")


def markdown_to_text(markdown: str) -> str:
    markdown = markdown.replace("\\r\\n", "\\n").replace("\\r", "\\n")
    markdown = FRONT_MATTER.sub("", markdown, count=1)
    lines = markdown.splitlines()
    out: list[str] = []
    in_fence = False

    for raw in lines:
        line = raw.rstrip()
        if LIQUID_INCLUDE.match(line):
            continue
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            out.append(line)
            continue

        match = HEADING.match(line)
        if match:
            level = len(match.group(1))
            title = strip_inline(match.group(2)).strip()
            if out and out[-1] != "":
                out.append("")
            out.append(title)
            if level <= 2:
                out.append("=" * len(title) if level == 1 else "-" * len(title))
            out.append("")
            continue

        if re.fullmatch(r"\\s*---+\\s*", line):
            if out and out[-1] != "":
                out.append("")
            continue

        if line.startswith("> "):
            line = line[2:]

        if re.match(r"^\\s*[-*+]\\s+", line):
            indent = len(line) - len(line.lstrip())
            line = " " * indent + "- " + re.sub(r"^\\s*[-*+]\\s+", "", line)

        out.append(strip_inline(line))

    normalized: list[str] = []
    for line in out:
        if line == "" and normalized and normalized[-1] == "":
            continue
        normalized.append(line.rstrip())

    return "\\n".join(normalized).strip() + "\\n"


def output_path() -> Path:
    release = json.loads(RELEASE.read_text(encoding="utf-8"))
    normative = release["normativeVersion"]
    return ROOT / "dist" / f"gaam-specification-v{normative}.txt"


def render() -> str:
    return markdown_to_text(SOURCE.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", type=Path, help="fail unless PATH exactly matches generated bytes")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        if not args.check.exists():
            raise SystemExit(f"missing generated artifact: {args.check}")
        existing = args.check.read_text(encoding="utf-8")
        if existing != rendered:
            raise SystemExit(f"plain-text artifact is stale: {args.check}")
        print(f"plain-text artifact current: {args.check}")
        return 0

    target = args.output or output_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8", newline="\\n")
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
